### PR TITLE
Add try catch

### PR DESCRIPTION
**Pull request by avtehnik**

### CODE REVIEW

**Comment by mcfedr** [comment]
Why does it need this?

**Comment by mcfedr** [comment]
Remeber that `try, catch` can have a bad effect on performance, especially inside a tight loop which this is.

**Comment by victorpaul** [comment]
this allListener call itself at the end (by default not offen than 100
mileseconds) , if user's callback failed than allListener failed as well

On Thu, May 21, 2015 at 3:39 PM, Fred Cox notifications@github.com wrote:

> Why does it need this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AppShed/ioio-cordova-plugin/pull/1#issuecomment-104256561
> .

## 

Sent from my IBM PS/2 Model 70-M61

**Comment by mcfedr** [comment]
I think the users callback failing is his problem and not one that you should worry about.

**Pull request merged**
